### ISSUE TITLE
can't create new ssl if uncheck subdomains option

### ISSUE THREAD

**Issue by iPokz** [Petertjuh360/da-letsencrypt#58] opened 2016-01-07 02:17 UTC
###### if uncheck Subdomains option will show this error message.

``` php
 Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/Domain.php on line 109 
```

but if checked subdomains option it work :+1: 
# 

OS : CentOS 6 (x64)
DirectAdmin with Custombuild
Apache 2.2 Web Server
PHP : 5.5.30

**Comment by Wouter0100** [comment] 2016-01-07 08:31
Duplicate of #40

**Closed as completed** 2016-01-07 11:01 UTC
Labels: duplicate
