### ISSUE TITLE
Invalid response: No registration exists

### ISSUE THREAD

**Issue by rezafathi** [Petertjuh360/da-letsencrypt#59] opened 2016-01-07 06:26 UTC
Hello,

When I want to enable SSL certificatre for a customer i faced with this error in Direct Admin.

---

Error while completing domain challenges

Details
## Invalid response: No registration exists matching provided key. Request URI: https://acme-v01.api.letsencrypt.org/acme/new-authz.

so what is the problem and how can i solve it? Thanks.

**Comment by Wouter0100** [comment] 2016-01-07 08:32
Delete the user's account using the delete button in the Let's Encrypt plugin. This should fix it. Did you change the server?

**Comment by rezafathi** [comment] 2016-01-07 08:46
I updated the plugin first and then deleted the account . That worked great. what about the renewal ? does it renew all certificates automatically? and how often it checks for renewal? thanks

**Comment by zenire** [comment] 2016-01-07 11:49
Yes it renews automatically. A cron runs every month and checks the expiry date. If needed the affected domains certificate will be renewed.

**Comment by Wouter0100** [comment] 2016-01-07 11:54
@Petertjuh360 It runs daily at 1:30.

**Comment by zenire** [comment] 2016-01-07 18:32
@Wouter0100 Sorry, my bad. Read it wrong.

I am closing the issue because the question of @rezafathi is answered and the problem is solved.

**Closed as completed by zenire** 2016-01-07 18:32 UTC
Labels: question
