### ISSUE TITLE
Allow any certificate valid or not to connect to directadmin

### ISSUE THREAD

**Issue by ictabc** [Petertjuh360/da-letsencrypt#53] opened 2015-12-28 20:08 UTC
Get the following error code when SSL=1: Using CACERT certificate.

Warning: stream_socket_client(): SSL: Connection reset by peer in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/HTTPSocket.php on line 198 Warning: stream_socket_client(): Failed to enable crypto in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/HTTPSocket.php on line 198 Warning: stream_socket_client(): unable to connect to ssl://127.0.0.1:2222 (Unknown error) in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/HTTPSocket.php on line 198

Openssl s_client works and gives correct certificate.

Need to disable SSL to make plugin work. At the moment, see also previous issue about requesting ssl cert for portal.

**Comment by Wouter0100** [comment] 2016-01-06 12:20
Hmm, strange. Is your DA port 2222? SSL should work fine.

**Comment by zenire** [comment] 2016-01-07 11:47
Could it be possible it fails when there is no valid SSL certificate?

**Comment by ictabc** [comment] 2016-01-07 15:15
I use cacert certificates at the moment, and ask my clients to install the root certificate for cacert to don't get error's. But I haven't added the root certificate to the server. So now da-letsencrypt checks the certificate. And find it's not acceptable because the root cert is not there.

Two options:

Option 1: connect to ssl://localhost:222 and allow connection if certificate valid or not.

Option 2: Add a function to install a letsencrypt cert for the local DA server. Issue #52 

I think option 2 is better than fixing this, unless it is possible and maybe can enable or disable the option to allow invalid/expired cert.

**Comment by Wouter0100** [comment] 2016-01-07 15:18
Hmm, wasn't that already disabled? See #19.

**Comment by ictabc** [comment] 2016-01-07 15:30
Well if that should have fixed it it isn't working for me with my cacert.org certificate, with a missing root cert in local root certificate store. But this can be closed if it is possible to request a certificate for the DA server default webpage and the also the DA web/management portal (:2222). 

Then this problem should go away altogether, when enabling the module you are able to request the certificate for the DA management portal/DA default website. So there is always a good certificate for the DA management portal.

**Comment by ictabc** [comment] 2016-01-07 16:11
Ok, added the cacrt root1 and root3 to the server ca bundle. But still this error. So something else.... But what.

**Comment by Wouter0100** [comment] 2016-01-13 21:54
What if you `curl` or `wget` `localhost:2222`?

**Comment by Wouter0100** [comment] 2016-01-21 10:36
I'm closing this issue, because I'm not able to reproduce it. When you still have this issue, don't hesitate to open it again.

**Closed as completed by Wouter0100** 2016-01-21 10:36 UTC
Labels: bug
